name: cattle_disease_ai
description: An offline-first Flutter mobile application for early cattle disease diagnosis.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ML & AI
  tflite_flutter: ^0.10.4
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
