[server]
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#c8102e"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#334155"
font = "sans serif"
